In [ ]:
import pandas as pd
import numpy as np
import ast
from collections import Counter

In [ ]:
df = pd.read_excel("PERCEPT.xlsx")
df.head()

,Text,Source,Topic,Platform,Words,POS,Positions,To Check,Result
0,سلام،اگر دیجی کالا محصولاتی مثل lexar professi...,MirasOpinion,برند و کسب‌وکار,Digikala,"['lexar', 'professional', '256GB', '540mb\\s',...","['PROPN', 'PROPN', 'NUM', 'SYM', 'NOUN']","['initial', 'initial', 'initial', 'medial', 'm...",NaN,"[{'word': 'lexar', 'upos': 'PROPN'}, {'word': ..."
1,با سلام خدمت دوستان من خودم M9 دارم و این یه چ...,MirasOpinion,برند و کسب‌وکار,Digikala,['M9'],['PROPN'],['initial'],NaN,"[{'word': 'M9', 'upos': 'PROPN'}]"
2,سلام دوستان.... من اینو خریدم چند ماه پیش ......,MirasOpinion,برند و کسب‌وکار,Digikala,"['vob', 'mpeg', 'هنگ']","['NOUN', 'NOUN', 'VERB']","['medial', 'medial', 'medial']",NaN,"[{'word': 'vob', 'upos': 'NOUN'}, {'word': 'mp..."
3,سلام این محصول رو امروز تهیه کردم البته به ع...,MirasOpinion,برند و کسب‌وکار,Digikala,"['wifi', 'hp', 'Device', 'Manager', 'Advanced'...","['NOUN', 'PROPN', 'NOUN', 'NOUN', 'ADJ', 'NOUN...","['medial', 'medial', 'medial', 'final', 'final...",NaN,"[{'word': 'wifi', 'upos': 'NOUN'}, {'word': 'h..."
4,متاسفانه برنامه ی دستگاه کاملا چینی هست که یه ...,MirasOpinion,برند و کسب‌وکار,Digikala,['اکانت'],['NOUN'],['initial'],NaN,"[{'word': 'اکانت', 'upos': 'NOUN'}]"

In [ ]:
df['Positions'] = df['Positions'].apply(ast.literal_eval)

In [ ]:
allPositions = []

for index, row in df.iterrows():
  allPositions.extend(row["Positions"])

In [ ]:
print(len(allPositions))

10785

In [ ]:
freq = Counter(allPositions)
for item, count in freq.items():
  print(item, count)

initial 3899
medial 3848
final 3038

In [ ]:
df_exp = df.explode("Positions")
df_exp = df_exp[df_exp["Positions"].notna()]

In [ ]:
counts = (
    df_exp
    .groupby(["Platform", "Positions"])
    .size()
    .reset_index(name="count")
)

In [ ]:
counts

    Platform Positions  count
0   Digikala     final   1026
1   Digikala   initial   1222
2   Digikala    medial   1242
3  Instagram     final    477
4  Instagram   initial    571
5  Instagram    medial    587
6    Twitter     final   1535
7    Twitter   initial   2106
8    Twitter    medial   2019