In [ ]:
import pandas as pd
import numpy as np
import ast
from collections import Counter
from itertools import chain

In [ ]:
df = pd.read_excel("PERCEPT.xlsx")
df.head()

,Text,Source,Topic,Platform,Words,POS,Positions,To Check,Result
0,سلام،اگر دیجی کالا محصولاتی مثل lexar professi...,MirasOpinion,برند و کسب‌وکار,Digikala,"['lexar', 'professional', '256GB', '540mb\\s',...","['PROPN', 'PROPN', 'NUM', 'SYM', 'NOUN']","['initial', 'initial', 'initial', 'medial', 'm...",NaN,"[{'word': 'lexar', 'upos': 'PROPN'}, {'word': ..."
1,با سلام خدمت دوستان من خودم M9 دارم و این یه چ...,MirasOpinion,برند و کسب‌وکار,Digikala,['M9'],['PROPN'],['initial'],NaN,"[{'word': 'M9', 'upos': 'PROPN'}]"
2,سلام دوستان.... من اینو خریدم چند ماه پیش ......,MirasOpinion,برند و کسب‌وکار,Digikala,"['vob', 'mpeg', 'هنگ']","['NOUN', 'NOUN', 'VERB']","['medial', 'medial', 'medial']",NaN,"[{'word': 'vob', 'upos': 'NOUN'}, {'word': 'mp..."
3,سلام این محصول رو امروز تهیه کردم البته به ع...,MirasOpinion,برند و کسب‌وکار,Digikala,"['wifi', 'hp', 'Device', 'Manager', 'Advanced'...","['NOUN', 'PROPN', 'NOUN', 'NOUN', 'ADJ', 'NOUN...","['medial', 'medial', 'medial', 'final', 'final...",NaN,"[{'word': 'wifi', 'upos': 'NOUN'}, {'word': 'h..."
4,متاسفانه برنامه ی دستگاه کاملا چینی هست که یه ...,MirasOpinion,برند و کسب‌وکار,Digikala,['اکانت'],['NOUN'],['initial'],NaN,"[{'word': 'اکانت', 'upos': 'NOUN'}]"

In [ ]:
df['POS'] = df['POS'].apply(ast.literal_eval)

In [ ]:
allPOS = []

for index, row in df.iterrows():
  allPOS.extend(row["POS"])

In [ ]:
freq = Counter(chain.from_iterable(df["POS"]))

for item, count in freq.items():
  print(item,count, "***", count/len(allPOS))

PROPN 1289 *** 0.1195178488641632
NUM 102 *** 0.009457579972183588
SYM 5 *** 0.0004636068613815484
NOUN 5981 *** 0.5545665275846082
VERB 1843 *** 0.17088548910523876
ADJ 1354 *** 0.12554473806212332
X 8 *** 0.0007417709782104776
ADP 34 *** 0.0031525266573945296
DET 18 *** 0.0016689847009735744
CCONJ 5 *** 0.0004636068613815484
ADV 81 *** 0.007510431154381085
INTJ 41 *** 0.0038015762633286975
PRON 16 *** 0.0014835419564209551
AUX 5 *** 0.0004636068613815484
PART 2 *** 0.0001854427445526194
SCONJ 1 *** 9.27213722763097e-05

In [ ]:
posPerPlatform = (
    df.groupby("Platform")["POS"]
      .apply(lambda col: Counter(chain.from_iterable(col)))
)

In [ ]:
posPerPlatform

Platform
Digikala   PROPN    1220.0
           NUM        88.0
           SYM         5.0
           NOUN     1583.0
           VERB      252.0
           ADJ       315.0
           X           3.0
           ADP        13.0
           DET         4.0
           CCONJ       2.0
           ADV         5.0
           INTJ        NaN
           PRON        NaN
           AUX         NaN
           PART        NaN
           SCONJ       NaN
Instagram  PROPN      11.0
           NUM         4.0
           SYM         NaN
           NOUN      979.0
           VERB      289.0
           ADJ       316.0
           X           4.0
           ADP         4.0
           DET         NaN
           CCONJ       NaN
           ADV        11.0
           INTJ       16.0
           PRON        1.0
           AUX         NaN
           PART        NaN
           SCONJ       NaN
Twitter    PROPN      58.0
           NUM        10.0
           SYM         NaN
           NOUN     3419.0
           VERB     1302.0
           ADJ       723.0
           X           1.0
           ADP        17.0
           DET        14.0
           CCONJ       3.0
           ADV        65.0
           INTJ       25.0
           PRON       15.0
           AUX         5.0
           PART        2.0
           SCONJ       1.0
Name: POS, dtype: float64